// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXc32N9Y6lojgraY403UjpQMaYJqb-ODI',
    appId: '1:808833610407:web:8234b023a8937b1eed6182',
    messagingSenderId: '808833610407',
    projectId: 'auth-tutorial-a8960',
    authDomain: 'auth-tutorial-a8960.firebaseapp.com',
    storageBucket: 'auth-tutorial-a8960.appspot.com',
    measurementId: 'G-T2TB5151MW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUr141FvuTX1BN5X7fW1T7CftiyTYDDs0',
    appId: '1:808833610407:android:2e237040a37823d1ed6182',
    messagingSenderId: '808833610407',
    projectId: 'auth-tutorial-a8960',
    storageBucket: 'auth-tutorial-a8960.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCotFZVSvIxv2GWI8TfQ_MVM5wyorAASjw',
    appId: '1:808833610407:ios:a2940595f4dfa019ed6182',
    messagingSenderId: '808833610407',
    projectId: 'auth-tutorial-a8960',
    storageBucket: 'auth-tutorial-a8960.appspot.com',
    iosClientId: '808833610407-qeljv5i90vp0sbj283q0dht9d3nq89gp.apps.googleusercontent.com',
    iosBundleId: 'com.example.authTutorial',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCotFZVSvIxv2GWI8TfQ_MVM5wyorAASjw',
    appId: '1:808833610407:ios:a2940595f4dfa019ed6182',
    messagingSenderId: '808833610407',
    projectId: 'auth-tutorial-a8960',
    storageBucket: 'auth-tutorial-a8960.appspot.com',
    iosClientId: '808833610407-qeljv5i90vp0sbj283q0dht9d3nq89gp.apps.googleusercontent.com',
    iosBundleId: 'com.example.authTutorial',
  );
}
